title: Cluster & PCA Analyses of Chem Libretexts Bookshelves, an Analysis of Inequity in Opensource Chemical Textbooks in Python
description: CS Final Project - Andrew Fisher
author: Andrew Fisher
theme: jekyll-theme-cayman
